### ISSUE TITLE
Create http endpoints on Node-RED

### ISSUE THREAD

**Issue by smithjilks** [QUALIS-LABS/IBM-Call-for-code-2021-zero-hunger-solution#5]
# Requirements
1. End points should receive respective data from app, USSD and SMS,  and update CoudantDB.
2. Backend should be able implement endpoints for initiating push notifications and broadcast SMS 
3. The end points should send back appropriate responses.
4. Node-RED instance should run on IBM Cloud.

# Tasks 
- [ ] Create http endpoints on Node-RED that CRUD CloudantDB instance.
- [ ] Create cloud messaging / Broadcast SMS infrastructure

**Comment by SammyOina** [comment]
Orchestration will be on IBM Cloud Kubernetes Service
